[configuration]
display = 0
simulation = 1
mqtt = 0
robot = 0
obstacle = 0
seed = 150
field = 2
debug = 0
waittime = 0
step = 999

[environment]
rows = 15
columns = 20

[display]
x = 10
y = 210
width = 1000
height = 750
title = Position Test

[color]
robot   = 0,120,255
goal    = 0,200,120
other   = 160,110,255
obstacle= 100,100,100
unknown = 180,180,180

[warehouse]
total_pallets = 20
arrival_probability = 0.15
arrival_distribution = binomial
num_obstacles = 0
num_humans = 2
num_amrs = 5
max_battery = 100
recharge_rate = 5
intermediate_capacity = 5

# Explicit positions: entries on TOP, exits on BOTTOM
entry_positions = 1:5,1:10,1:15
exit_positions = 13:5,13:15
intermediate_positions = 7:8,7:12
recharge_positions = 7:3,7:17
obstacle_positions = 4:7,4:13,10:7,10:13
